%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-image-rotate
Version:        6.0.10
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS image_rotate package

License:        BSD
URL:            https://index.ros.org/p/image_rotate/github-ros-perception-image_pipeline/
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-kilted-cv-bridge
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-image-transport
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rclcpp-components
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-tf2
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-tf2-ros
Requires:       ros-kilted-ros-workspace
BuildRequires:  opencv-devel
BuildRequires:  ros-kilted-ament-cmake-auto
BuildRequires:  ros-kilted-class-loader
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-image-transport
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rclcpp-components
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-tf2
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
%endif

%description
Contains a node that rotates an image stream in a way that minimizes the angle
between a vector in some arbitrary frame and a vector in the camera frame. The
frame of the outgoing image is published by the node. This node is intended to
allow camera images to be visualized in an orientation that is more intuitive
than the hardware-constrained orientation of the physical camera. This is
particularly helpful, for example, to show images from the PR2's forearm cameras
with a consistent up direction, despite the fact that the forearms need to
rotate in arbitrary ways during manipulation. It is not recommended to use the
output from this node for further computation, as it interpolates the source
image, introduces black borders, and does not output a camera_info.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.10-2
- Autogenerated by Bloom

* Thu Feb 27 2025 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.10-1
- Autogenerated by Bloom

* Thu Feb 13 2025 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.9-1
- Autogenerated by Bloom

* Mon Feb 10 2025 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.8-1
- Autogenerated by Bloom

* Fri Dec 27 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.7-1
- Autogenerated by Bloom

* Wed Dec 11 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.6-1
- Autogenerated by Bloom

* Wed Oct 30 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.5-1
- Autogenerated by Bloom

* Wed Oct 16 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.4-1
- Autogenerated by Bloom

* Tue Aug 20 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.3-1
- Autogenerated by Bloom

* Tue Jul 23 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.2-1
- Autogenerated by Bloom

* Mon Jul 22 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.1-1
- Autogenerated by Bloom

* Tue Jun 04 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 6.0.0-2
- Autogenerated by Bloom

* Tue Mar 26 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 5.0.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Vincent Rabaud <vincent.rabaud@gmail.com> - 5.0.0-2
- Autogenerated by Bloom

